image: docker:git
services:
  - docker:dind

variables:
  REGISTRY_BASE: registry.gitlab.com/nyker510/${CI_PROJECT_NAME}
  # [HOTFIX]: gitlab のバグでないと Docker in Docker のデーモンにアクセスできないっぽい
  DOCKER_TLS_CERTDIR: ''


before_script:
  - export TEST_IMAGE=${REGISTRY_BASE}/test 
  - export PATH=~/.local/bin:/usr/bin/:$PATH
  - apk update
  - apk --no-cache add --update curl bash jq python python-dev py-pip
  - pip install -U pip
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - build
  - test

# build image for test context
build-test:
  stage: build
  script:
    - docker build -t ${TEST_IMAGE} .
    - docker push ${TEST_IMAGE}
  only:
    refs:
      - master

test:
  stage: test
  script:
    - export LOGLEVEL=INFO
    - docker pull ${TEST_IMAGE}
    - docker run -v ${PWD}:/workspace ${TEST_IMAGE} pytest -v --cov=./vivid/
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - dist
